version: '3.8'
services:
  # mysql:
  #   image: mysql:5.7
  #   container_name: mysql-shoparound-c-sharp
  #   ports:
  #   - "3306:3306"
  #   command: --default-authentication-plugin=mysql_native_password
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: Test.1234
  #     MYSQL_DATABASE: zemart
  #     MYSQL_USER: zemart-client
  #     MYSQL_PASSWORD: Test.1234
  
  postgres:
    container_name: postgres-shoparound
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shoparound
    volumes:
       - shoparound:/data/postgres
    ports:
      - "5432:5432"
    restart: always

  shopearound_identity:
    container_name: postgres-shopearound-identity
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shopearound-identity
    volumes:
       - shopearound-identity:/data/postgres
    ports:
      - "5433:5433"
    restart: always


volumes:
  shoparound:
  shopearound-identity: